### ISSUE TITLE
iOS 8.1.3 (on iPhone 6, iPad Mini Retina): Simlar doesn't start normally

### ISSUE THREAD

**Issue by dutty5** [simlar/simlar-ios#29]
On iOS 8.1.3 (iPhone 6, iPad Mini Retina) Simlar doesn't start normally. Its window keeps open in the background (visible through task switch) but cannot be made to stay on the foreground when selected.

**Comment by BenSartor** [comment]
Hi dutty5,
thank you for reporting the bug. It is fixed in the next release (0.0.3) which we just uploaded to app store right now. But it might take some days for Apple to approve the upload.

What is the problem?
Simlar in version 0.0.2 is a 32 bit App. In the iOS Update 8.1.3 Apple removed 32 bit PushKit which triggers the crash.

Solution:
Support 64 bit builds.

Cheers,
 Ben
